US20499 Add Resi Player
crdschurch/crds-net pull request #1997
Opened 2021-01-08 18:36 UTC by silasbaur

2021-01-11 22:01 UTC, dholloran-ample requested changes
@silasbaur

- I left a few syntax/improvement related comments.
- It does not refresh when it is past the end time (Not sure if that was intended to work)

2021-01-12 15:02 UTC, silasbaur commented on _assets/javascripts/components/resi-player.js
> +  const startDate = new Date();
Not sure if this solution will work with two different service start times.

2021-01-12 16:05 UTC, dholloran-ample approved these changes

2021-01-12 16:07 UTC, dholloran-ample commented
Holding merging into `int` until time test Wednesday/Thursday (Jan 13/14)

2021-01-13 15:09 UTC, merged