Feature/us21036 author template update
crdschurch/crds-net pull request #2349
Opened 2021-07-08 17:09 UTC by laurasprauer

## Problem
*Document current behaviour and why it's undesirable here.*

## Solution
*Document how the behaviour was fixed here.*

### Corresponding Branch
*Add link to crdschurch/repo-name-here#issue-number (if applicable). This helps the code reviewer know that corresponding work exists and where to find it.*

## Testing
*Include information on how to test your work here (if applicable).*

2021-07-09 14:13 UTC, silasbaur requested changes
A couple of inline comments. Let me know if you want to talk through anything
1. This image is not rendering correctly something is wrong with imgix optimizer here. Also this image is way too tall. Should have a height of 410px
![Screen Shot 2021-07-09 at 9 59 15 AM](https://user-images.githubusercontent.com/32345656/125089373-5590b900-e09c-11eb-9647-ae23ff835c58.png)
2. I would not include podcast here. Just include episodes and other media. Podcasts will not show a duration and it will look weird.
![Screen Shot 2021-07-09 at 10 01 12 AM](https://user-images.githubusercontent.com/32345656/125089724-9a1c5480-e09c-11eb-8c25-bc2b9fbec9cd.png)
3. I fixed the crds-media-object image. `data-optimize-img` does not work on components very well. Once the image component is fixed we should not have problems anymore. I just added
4. I also fixed the author image. When you first load the page, the image was small and then became bigger. I fixed this by adding a class of `full-width`.
5. These images are messed up here. I would take a look at where else we have cards similar to this and copy what they are doing.
![Screen Shot 2021-07-09 at 10 05 26 AM](https://user-images.githubusercontent.com/32345656/125090302-321a3e00-e09d-11eb-86df-993c94384dbd.png)

2021-07-09 14:13 UTC, silasbaur commented on _layouts/author.html
> +      <crds-tabs tabs='{{tabs_array | jsonify }}' mobile-dropdown navigation-class="align-tabs-left">
I like what you did here!

2021-07-12 12:33 UTC, laurasprauer commented on _layouts/author.html
>  {% assign author = site.authors | where: 'full_name', page.title | first %}
I think I need to keep this as is - page.author is not defined

2021-07-12 13:03 UTC, laurasprauer commented
@silasbaur fixes are up!

I'm not sure how to fix the article heroes height issue however (number 1 in your list)
I pulled the code from the hero on the articles pages - is there a better place to pull this code from? or did you want me to set a hard height on these images?

2021-07-13 17:44 UTC, dholloran-ample requested changes
@laurasprauer 

- Left 2 inline comments
- For the image issue I wonder if we need to use `<crds-image />` for the images. Have you tried loading them outside of the `<crds-tabs />` component? I wonder if it is related to something stencil does?

2021-07-13 18:28 UTC, laurasprauer commented
@dholloran-ample I pushed up all your fixes - I added a max-height to the image issue, apparently this was a style included on the articles page (where I copied this code from) that I had missed, it should look the same now! However it's still "fuzzy" while the one on the individual article page is not, even tho they are essentially using the same code? but it looks like all the images are "fuzzy" - is this just because so many are getting loaded at once and it's a dev env?

2021-07-15 19:39 UTC, dholloran-ample approved these changes

2021-07-15 19:39 UTC, merged