US21921 Groups Tab
crdschurch/crds-net pull request #2482
Opened 2021-11-30 16:37 UTC by silasbaur

## Problem
[US21921](https://rally1.rallydev.com/#/?detail=/userstory/618243719611&fdp=true): Add groups tab to location pages

## Solution
Add groups tab to both location templates
[Oakley Preview](https://groups-tab--int-crds-net.netlify.app/oakley)
[Columbus Preview](https://groups-tab--int-crds-net.netlify.app/columbus)

2021-12-02 11:16 UTC, tcmacdonald requested changes

2021-12-02 11:16 UTC, tcmacdonald commented on _layouts/established.html
> +              <p>The people you surround yourself with have a direct impact on the quality of your life. From lifestage to shared interests, in homes or online, there are hundreds of groups ready for
Can this content be moved to a partial or ideally a content block?

2021-12-02 19:09 UTC, silasbaur commented
This can not go live until 12-13

2021-12-06 13:38 UTC, tcmacdonald approved these changes

2021-12-06 14:10 UTC, closed without merging