annual report file with annual report component
crdschurch/crds-net pull request #3226
Opened 2023-12-19 15:33 UTC by milenbteam

## Problem
*Document current behaviour and why it's undesirable here.*

## Solution
*Document how the behaviour was fixed here.*

### Corresponding Branch
*Add link to crdschurch/repo-name-here#issue-number (if applicable). This helps the code reviewer know that corresponding work exists and where to find it.*

## Testing
*Include information on how to test your work here (if applicable).*

2023-12-19 15:48 UTC, jodylane approved these changes

2023-12-19 15:50 UTC, jodylane requested changes
I did not mean to approve this the tag name appears to be incorrect here. in crds components you defined you component as 
`site-annual-reports`

2023-12-19 15:58 UTC, milenbteam commented
> I did not mean to approve this the tag name appears to be incorrect here. in crds components you defined you component as `site-annual-reports`

I thought that the components are called with their folder's name. I changed the tag.

2023-12-19 16:07 UTC, jodylane requested changes
you still have a typo here heres documentation regarding stencil component tag decorator https://stenciljs.com/docs/component#tag

2023-12-21 16:59 UTC, bbbtttiii approved these changes

2023-12-21 20:39 UTC, merged