add service times to config
crdschurch/crds-net pull request #3266
Opened 2024-02-01 18:01 UTC by jacobtellep

## Problem
*Document current behaviour and why it's undesirable here.*

## Solution
*Document how the behaviour was fixed here.*

### Corresponding Branch
*Add link to crdschurch/repo-name-here#issue-number (if applicable). This helps the code reviewer know that corresponding work exists and where to find it.*

## Testing
*Include information on how to test your work here (if applicable).*

2024-02-08 14:48 UTC, jodylane requested changes

2024-02-08 14:48 UTC, jodylane commented on _includes/_location-info.html
>          {% endfor %}
one issue I see here with this solution is that there was a desire to have the order of the service times display change based on the order service times were added on the location.

2024-02-09 21:25 UTC, sscarberry commented
Got a little boo boo here on the /locations pages:
![image](https://github.com/crdschurch/crds-net/assets/45611651/fe8e4f11-b8b7-48b4-9d18-65b1241eb23e)
![image](https://github.com/crdschurch/crds-net/assets/45611651/d3e68c82-1304-416b-bb00-0c5058445ba6)

Also we missed the service times block on the bespoke locations template i.e. /oakley
![image](https://github.com/crdschurch/crds-net/assets/45611651/66acf78e-e36f-4d87-9f69-61747fe12ae2)

2024-02-09 21:27 UTC, sscarberry commented
Additional to my comment - it looked like the changes are made, but not working correctly.

2024-02-09 21:28 UTC, sscarberry requested changes

2024-02-09 21:28 UTC, sscarberry commented on _includes/_location-info.html
> +        {% assign current_date = "now" | date: "%s" %}
These dates don't appear to be rendering correctly based on contentful config

2024-02-14 15:44 UTC, jodylane approved these changes
this appears to be functioning

2024-02-14 15:44 UTC, jodylane commented
![Uploading Screen Shot 2024-02-14 at 10.44.21 AM.png…]()

2024-02-15 04:06 UTC, sscarberry approved these changes

2024-02-20 18:58 UTC, merged