Adjust bash script to exclude our-memories.html file when processing …
crdschurch/crds-net pull request #3269
Opened 2024-02-02 21:50 UTC by mjvezzani

…image tags

## Problem
Images on `/our-memories` are not displaying correctly.

## Solution
`?auto=compress` was getting appended to the end of image src tags that already had `?auto=format,compress` in the source url. `?auto=compress` was being appended in the `update-image-urls.sh` shell script that only runs when a `netlify build` is run, resulting in the problem manifesting in `demo` and `prod` but not locally.

In the `update-image-urls.sh` the existing logic has been wrapped in an additional if statement checking to see if the file is the `our-memories.html` file. If it is, then it gets skipped over. Otherwise, the logic proceeds as it previously did.

## Testing
Navigate to `/our-memories` and see if images are loading and displaying correctly.

2024-02-02 22:24 UTC, mjvezzani commented
Please hold. This still has some kinks to work out.

2024-02-05 19:32 UTC, mjvezzani commented
Alright. This should be good to review.

2024-02-06 17:27 UTC, sscarberry requested changes

2024-02-06 17:27 UTC, sscarberry commented on bin/update-image-urls.sh
> +  echo "$file"
can remove this echo now

2024-02-06 18:07 UTC, merged