Added null check for author
crdschurch/crds-net pull request #3287
Opened 2024-03-07 12:14 UTC by yordanthebteam

## Problem
*Document current behaviour and why it's undesirable here.*

## Solution
*Document how the behaviour was fixed here.*

### Corresponding Branch
*Add link to crdschurch/repo-name-here#issue-number (if applicable). This helps the code reviewer know that corresponding work exists and where to find it.*

## Testing
*Include information on how to test your work here (if applicable).*

2024-03-12 15:17 UTC, jodylane reviewed
I think the point of this task was to remove the null authors from this page not to replace them with a hard coded author. 

we've solved this in other areas by filtering null values out of the original data set or adding a conditional around the section that would render the author to check that data is not null. Ill have to check with PM's to see if this would also be an acceptable solution.

2024-03-12 17:38 UTC, jodylane requested changes
build still fails when contentful demo environment has a published article with a drafted author.

2024-03-14 19:17 UTC, sscarberry approved these changes

2024-03-14 19:24 UTC, sscarberry approved these changes

2024-03-14 19:35 UTC, merged